---
application:
  name: "pwa-homework"
  project: "test-db"
  organization: "QoveryCommunity"
databases:
- type: "MYSQL"
  name: "star"
  version: "8.0"
routers:
- name: "main-pwa-homework"
  routes:
  - application_name: "pwa-homework"
    paths:
    - "/*"
